baseURL = "https://occ-barber.netlify.com/"
languageCode = "en-us"
title = "Corner Barber Shop"
MetaDataFormat = ""
theme = "hugo-base-theme"

[params]
    description = "Your Neighborhood Barber"
    style = "default"
    mainIcon = "img/blogo.png"

[indexes]
    category = "categories"
    tag = "tags"
    group = "groups"

[menu]

    [[menu.main]]
        name = "Home"
        url = "#"
        weight = 1
    [[menu.main]]
        name = "Services"
        url = "/post/services/"
        weight = 2
    [[menu.main]]
        name = "Products"
        url = "/post/products/"
        weight = 3
    [[menu.main]]
        name = "About"
        url = "/post/about/"
        weight = 4