baseURL = "localhost:1313/"
languageCode = "en-us"
title = "Corner Barber Shoppe"
MetaDataFormat = ""
theme = "hugo-base-theme"

[params]
    description = "Your Neighbourhood Barber"
    style = "default"
    mainIcon = "img/blogo.png"

[indexes]
    category = "categories"
    tag = "tags"
    group = "groups"

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-download'></i>"
    url = "/"
    weight = -200
[[menu.main]]
    name = "Services"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/post/services/"
    weight = -180
[[menu.main]]
    name = "Products"
    pre = "<i class='fa fa-comments'></i>"
    url = "/post/products/"
    weight = -150
