baseURL = "https://occ-barber.netlify.com/"
languageCode = "en-us"
title = "Corner Barber Shop"
MetaDataFormat = ""
theme = "hugo-base-theme"

[params]
    description = "Your Neighborhood Barber"
    style = "default"
    mainIcon = "img/blogo.png"

[indexes]
    category = "categories"
    tag = "tags"
    group = "groups"


[[menu.main]]
	name = "Home"
  url = "#"

[[menu.main]]
  name = "Services"
  url = "#/services/"

[[menu.main]]
  name = "Products"
	pre = "<i class='fa fa-desktop'></i>"
  url = "#/products/"

[[menu.main]]
  name = "About"
	pre = "<i class='fa fa-heart'></i>"
	identifier = "about"
  url = "#/about/"

[[menu.main]]
  name = "Showcase"
  pre = "<i class='fa fa-cubes'></i>"
  url = "/showcase/"
